#:schema https://raw.githubusercontent.com/cloudflare/wrangler2/sys-types/schema.json
name = "futa-landing"
compatibility_date = "2025-04-08"
compatibility_flags = ["nodejs_compat", "disable_nodejs_process_v2"]
pages_build_output_dir = "./dist"

[[kv_namespaces]]
binding = "FTM_SESSION"
id = "a1aaf0bc0d2b4f1c880439a328acefd6"

[[kv_namespaces]]
binding = "FTM_KV"
id = "02d875955965498c853be907d62dbc8c"
