name: Deploy to Firebase Everyday When New Video Update
on:
  schedule:
    - cron: '0 17 * * *' # 17.00 UTC-> 0.00 WIB
    - cron: '0 23 * * *' # 23.00 UTC-> 6.00 WIB
    - cron: '0 5 * * *' # 5.00 UTC-> 12.00 WIB
    - cron: '0 11 * * *' # 11.00 UTC-> 18.00 WIB

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FUTAMI_LANDING }}
          channelId: live
          projectId: futami-landing
